name: Docs

on:
  push:
    paths:
      - 'docusaurus/**'

jobs:
  gh-pages:
    name: "Github pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Yarn install
        run: yarn --cwd docusaurus/ install
      - name: Yarn build
        run: yarn --cwd docusaurus/ build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docusaurus/build
          external_repository: project-openubl/xbuilder-server-docs
          publish_branch: master
